# dataset creation parameters
dataset_parameters:
  database_folder: 'database'
  train_size: 0.7     #training set size
  test_size: 0.1      #test set size
  seed: 111           #seed for randomness in training/test split

visualisation:
  bounds: [0.1, 0.2, 0.5, 1, 2, 4, 7, 10, 20]